server:
  port: 8004
spring:
  application:
    name: cloud-provider-payment
  cloud:
    zookeeper:
      connect-string: localhost:2181
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      # 数据源
    driver-class-name: com.mysql.jdbc.Driver     # mysql驱动包
    url: jdbc:mysql://localhost:3306/order?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: "@Wangkai70264010"
